### ISSUE TITLE
Honour Validation attributes

### ISSUE THREAD

**Issue by benfoster** [aspnet/JsonPatch#18]
Currently only type checking is performed. It would be good if the object adaptor also honoured validation attributes on the object for example:

```
        [Range(18, 65)]
        public int Age { get; set; }
```

Currently I could set the age property to `10` using a patch operation.

**Comment by dougbu** [comment]
Object validation of HTTP data using validation attributes is an MVC feature. What is your end-to-end scenario? Why have you chosen not to use MVC in this scenario?

**Comment by benfoster** [comment]
We are using MVC. In the above scenario we'd have to manually invoke the validator on every patched object. You're currently doing type checking - it would be good if we had the ability to override this behaviour to also perform additional validation.

**Comment by Eilon** [comment]
Seems reasonable to me, but this isn't planned at this time.

**Comment by AymanGaafar** [comment]
Maybe you could do a separate Package to augment JsonPatch for MVC purposes, like `Microsoft.AspNetCore.JsonPatch.MVC`, which will have Validation Attributes and Bind Attribute checking.

**Comment by arielcloud** [comment]
+1 for this feature

**Comment by arielcloud** [comment]
Also, It'll be great to honour validation rules of _fluentValidation_

**Comment by RehanSaeed** [comment]
For those looking for a solution to this, you need to call `TryValidateModel` which adds any model errors to the `ModelState` for you and then you can check the model:

```
// Check that JSON patch document is valid.
if (!this.ModelState.IsValid)
{
    return this.BadRequest(this.ModelState);
}

patch.SafeApplyTo(model, this.ModelState);
this.TryValidateModel(model);
// Check that modified model is valid.
if (!this.ModelState.IsValid)
{
    return this.BadRequest(this.ModelState);
}
```

It's also worth noting that the JSON patch document could also be invalid, so you need to check the model state twice.

If you are using ASP.NET Core 1.0, then note that `ApplyTo` throws exceptions if the JSON patch document is invalid (More info [here](https://github.com/aspnet/Mvc/issues/5463)). This was fixed in ASP.NET Core 1.1, where it adds model state errors instead.

**Comment by Eilon** [comment]
Closing because there are no plans to implement this.

Using `TryValidateModel` is the best way to do this.

**Comment by RehanSaeed** [comment]
@Eilon Is this because of the disconnect between ASP.NET Core and MVC? I've heard there are plans to remove that disconnect although that statement is vague, could this issue be reopened once that happens?
