### ISSUE TITLE
AspNetCore.Mvc.Formatters.Json 1.1.1 should reference JsonPatch 1.1.1

### ISSUE THREAD

**Issue by PartyArk** [aspnet/JsonPatch#60]
Hi, I opened https://github.com/aspnet/JsonPatch/issues/48 which has resulted in a fix. Great! Thanks.

However, on updating AspNetCore.Mvc to 1.1.1, the reference chain doesn't reference this update to JsonPatch. Specifically AspNetCore.Formatters.Json still references the 1.1.0 version.

Maybe I'm misunderstanding how it should work. I can't (yet?) reference JsonPatch 1.1.1 separately.

**Comment by rynowak** [comment]
There isn't a JsonPatch `1.1.1`, `1.1.0` is the newest release.

**Comment by PartyArk** [comment]
You'll see the issue that I referenced was patched is in 1.1.1 and you can see https://github.com/aspnet/JsonPatch/milestone/10 that 1.1.1 is complete.

**Comment by kichalla** [comment]
@rynowak there is a branch 'rel/1.1.1' which i had earlier pushed my fix to. Probably @PartyArk is right about referencing it from MVC's 1.1.1 branch?

**Comment by PartyArk** [comment]
I think it may be too late for the MVC 1.1.1 branch, but could we at least reference the package separately via NuGet? I'm not sure what the process is for publishing it, but right now I can only see 1.1.0 or the 1.2.0 preview stuff.

**Comment by Eilon** [comment]
MVC 1.1.2's JsonFormatter library will reference JsonPatch 1.1.1. You can see that in this branch here: https://github.com/aspnet/Mvc/blob/rel/1.1.2/src/Microsoft.AspNetCore.Mvc.Formatters.Json/project.json#L24 . We expect this release to be available publicly within a few weeks.

The MVC 1.1.1 release was completed before JsonPatch 1.1.1 was available, so that's why it wasn't updated.
